name: Build Overlord Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Force Gradle 8.10
        run: |
          wget https://services.gradle.org/distributions/gradle-8.10-bin.zip
          unzip -d /opt/gradle gradle-8.10-bin.zip
          echo "/opt/gradle/gradle-8.10/bin" >> $GITHUB_PATH

      - name: Build with Gradle
        run: |
          gradle clean build --no-daemon

      - name: Upload Finished Mod
        uses: actions/upload-artifact@v4
        with:
          name: Overlord-Mod-Jar
          path: build/libs/*.jar
          if-no-files-found: error
